### ISSUE TITLE
这个UI可以给负分!!

### ISSUE THREAD

**Issue by hzxie** [ideaworld/BioDesigner#1]
贴几张图, 你们随意感受一下.

**页面中的 Logo 无法加载**
![2015-09-19 18 40 49](https://cloud.githubusercontent.com/assets/1730504/9975831/3b9bf4a4-5efe-11e5-8a9f-74fd49b10858.png)

**滚动条很诡异有没有**
![2015-09-19 18 41 15](https://cloud.githubusercontent.com/assets/1730504/9975833/490b770e-5efe-11e5-8096-565e36b3e50c.png)

**Comment by bowen1993** [comment]
这是张宇霄的设计大作加上前段的编写就不知道怎么就成这个德行了。。。要不我把后台接口给你你愉快的写一写前端？
巩 博文 Bowen Gong
E-mail: gbwlovehp@gmail.com

**Comment by hzxie** [comment]
最近并没有时间!!
这UI 我都不忍直视了好吗!!
争取抽时间帮你改一下登录页面吧.

2015-09-19 18:49 GMT+08:00 ideaworld notifications@github.com:

> 这是张宇霄的设计大作加上前段的编写就不知道怎么就成这个德行了。。。要不我把后台接口给你你愉快的写一写前端？
> 巩 博文 Bowen Gong
> E-mail: gbwlovehp@gmail.com
> 
> > 在 2015年9月19日，下午6:43，Howard Shieh notifications@github.com 写道：
> > 
> > 贴几张图, 你们随意感受一下.
> > 
> > 页面中的 Logo 无法加载
> > <
> > https://cloud.githubusercontent.com/assets/1730504/9975831/3b9bf4a4-5efe-11e5-8a9f-74fd49b10858.png
> > 
> > 滚动条很诡异有没有
> > <
> > https://cloud.githubusercontent.com/assets/1730504/9975833/490b770e-5efe-11e5-8096-565e36b3e50c.png
> > 
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/ideaworld/BioDesigner/issues/1>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ideaworld/BioDesigner/issues/1#issuecomment-141644148
> .

## 

谢浩哲

**Comment by bowen1993** [comment]
其实上一个版本的还好，然后改设计了，然后就呵呵了
